export const city = [
	{ key: 'GjithKosova', text: 'Gjith Kosova', value: 'Gjith Kosova' },
	{ key: 'Artanë', text: 'Artanë', value: 'Artanë' },
	{ key: 'Besianë', text: 'Besianë', value: 'Besianë' },
	{ key: 'Burim', text: 'Burim', value: 'Burim' },
	{ key: 'Dardanë', text: 'Dardanë', value: 'Dardanë' },
	{ key: 'Deçan', text: 'Deçan', value: 'Deçan' },
	{ key: 'Dragash', text: 'Dragash', value: 'Dragash' },
	{ key: 'Drenas', text: 'Drenas', value: 'Drenas' },
	{ key: 'Ferizaj', text: 'Ferizaj', value: 'Ferizaj' },
	{ key: 'Fushë Kosovë', text: 'Fushë Kosovë', value: 'Fushë Kosovë' },
	{ key: 'Gjakovë', text: 'Gjakovë', value: 'Gjakovë' },
	{ key: 'Gjilan', text: 'Gjilan', value: 'Gjilan' },
	{ key: 'Kastriot', text: 'Kastriot', value: 'Kastriot' },
	{ key: 'Kaçanik', text: 'Kaçanik', value: 'Kaçanik' },
	{ key: 'Klinë', text: 'Klinë', value: 'Klinë' },
	{ key: 'Leposaviq', text: 'Leposaviq', value: 'Leposaviq' },
	{ key: 'Lipjan', text: 'Lipjan', value: 'Lipjan' },
	{ key: 'Malishevë', text: 'Malishevë', value: 'Malishevë' },
	{ key: 'Mitrovicë', text: 'Mitrovicë', value: 'Mitrovicë' },
	{ key: 'Pejë', text: 'Pejë', value: 'Pejë' },
	{ key: 'Prishtine', text: 'Prishtine', value: 'Prishtine' },
	{ key: 'Prizren', text: 'Prizren', value: 'Prizren' },
	{ key: 'Rahovec', text: 'Rahovec', value: 'Rahovec' },
	{ key: 'Skenderaj', text: 'Skenderaj', value: 'Skenderaj' },
	{ key: 'Shtërpcë', text: 'Shtërpcë', value: 'Shtërpcë' },
	{ key: 'Shtime', text: 'Shtime', value: 'Shtime' },
	{ key: 'Therandë', text: 'Therandë', value: 'Therandë' },
	{ key: 'Viti', text: 'Viti', value: 'Viti' },
	{ key: 'Vushtrri', text: 'Vushtrri', value: 'Vushtrri' },
	{ key: 'Zubin Potok', text: 'Zubin Potok', value: 'Zubin Potok' },
	{ key: 'Zveçan', text: 'Zveçan', value: 'Zveçan' },
];
